.TH "filedata" 3 "Onegin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
filedata
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBfl\fP"
.br
.ti -1c
.RI "size_t \fBsz\fP"
.br
.ti -1c
.RI "int \fBnlns\fP"
.br
.ti -1c
.RI "char * \fBrdbffr\fP"
.br
.ti -1c
.RI "\fBstring\fP * \fBprsdbffr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "FILE* filedata::fl"

.SS "int filedata::nlns"

.SS "\fBstring\fP* filedata::prsdbffr"

.SS "char* filedata::rdbffr"

.SS "size_t filedata::sz"


.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin from the source code\&.
