.TH "io_data" 3 "Onegin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io_data
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBinp\fP"
.br
.ti -1c
.RI "const char * \fBout\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const char* io_data::inp"

.SS "const char* io_data::out"


.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin from the source code\&.
