.TH "sqsort.h" 3 "Onegin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqsort.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsqsort\fP (void *arr, size_t arrsize, size_t elemsize, int(*cmp)(const void *, const void *))"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void sqsort (void * arr, size_t arrsize, size_t elemsize, int(* cmp )(const void *, const void *))"
Sorts an array using the square algorithm\&.

.PP
\fBParameters\fP
.RS 4
\fIarr\fP The array to sort\&. 
.br
\fIarrsize\fP The size of the array\&. 
.br
\fIelemsize\fP The size of each element\&. 
.br
\fIcmp\fP The comparison function\&.
.RE
.PP
\fBNote\fP
.RS 4
The pointer to the array must be void*\&. 

.PP
Comparator must return 0 if elements are equal, positive int if first elem > second elem, negative int if first elem < second elem\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin from the source code\&.
