.TH "string" 3 "Onegin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
string
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBstr\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "size_t string::len"

.SS "const char* string::str"


.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin from the source code\&.
