.TH "structs.h" 3 "Onegin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
structs.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBstring\fP"
.br
.ti -1c
.RI "struct \fBfiledata\fP"
.br
.ti -1c
.RI "struct \fBio_data\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin from the source code\&.
